version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - data:/data
  weaviate:
    image: semitechnologies/weaviate:1.20.2
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
    - '5051:8080'
    restart: on-failure
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai,generative-openai,ref2vec-centroid,text2vec-contextionary'
      OPENAI_APIKEY: $OPENAI_APIKEY
      QUERY_DEFAULTS_LIMIT: 25
      CONTEXTIONARY_URL: contextionary:9999
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /var/weaviate:/var/lib/weaviate
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    container_name: contextionary
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    ports:
    - '9999:9999'
  streamlit:
    image: navi-demo
    container_name: streamlit
    restart: always
    depends_on:
        - redis
        - weaviate
        - contextionary
    build:
      context: .
    ports:
      - '8501:8501'
volumes:
  data: