[passwords]
ok_boomer = "fool"
simp_millenial = "millenial"
gen_xyz = "nocap"

[llms]
openai_api_key = ""
serpapi_api_key = ""

[redis]
host = "localhost"
port = 6379
password = "predis"

[weaviate]
host = "localhost"
port = 5051

[spotify]
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:8501/Content_Recommendations"

[newsapi]
api_key = ""